---
- name: Automatic Backup of Running-config
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
   - name: Backup CSR1000V Running-Config
     ios_config:
       backup: yes
       backup_options:
         dir_path: /home/devasc/labs/devnet-src/ansible/backups
     register: output
