---
- name: Configure CSR1000V
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
  - name: Configure Banner Login
    ios_banner:
      banner: login
      text: |
        #######################################
        #     CSR1000V on DevNet Sandbox      #
        #                                     #
        #  Unauthorized Access is Prohibited  #
        #######################################

        User Access Verification
      state: present

  - name: Configure Banner MOTD
    ios_banner:
      banner: motd
      text: |
        Welcome to the DevNet Sandbox CSR1000v and IOS XE
        
        Automation using Ansible and bash script
        for TSA NP Project
      state: present 

  - name: Configure Hostname
    ios_config:
      lines: hostname csr1kv

  - name: Configure Domain Lookup
    ios_config:
      lines:
        - no ip domain lookup

  - name: Configure password priviledge
    ios_config:
      lines:
        - enable secret C1sco12345

  - name: Configure password Console
    ios_config:
      parents: "line console 0"
      lines:
        - password C1sco12345
        - login

  - name: Encryption Password
    ios_config:
      lines:
        - service password-encryption

  - name: Configure Interface Gig2 IP Addresses
    ios_config:
      parents: "interface GigabitEthernet2"
      lines:
        - description IPv4 ADDRESS
        - ip address 192.168.2.1 255.255.255.224
        - no shutdown

  - name: Configure Interface Gig3 IP Addresses
    ios_config:
      parents: "interface GigabitEthernet3"
      lines:
        - description IPv4 ADDRESS
        - ip address 10.10.30.1 255.255.255.0
        - no shutdown

  - name: Configure IPv6 Address
    ios_config:
      parents: "interface GigabitEthernet3"
      lines:
        - description IPv6 ADDRESS
        - ipv6 address 2001:DB8:ACAD:1::1/64
        - ipv6 address FE80::1:1 link-local

  - name: Configure Domain Name
    ios_config:
      lines:
        - ip domain name devnet-project.com
        -  username developer secret C1sco12345

  - name: Configure Remote Password
    ios_config:
      parents: "line vty 0 15"
      lines:
        - login local
        - transport input ssh

  - name: Configure Remote SSH
    ios_config:
      lines:
        - crypto key generate rsa general-keys modulus 1024
        - ip ssh version 2

  - name: save running to start-config when modified
    ios_config:
      save_when: modified
